### ISSUE TITLE
Export `empty!` ?

### ISSUE THREAD

**Issue by Datseris** [Jutho/SparseArrayKit.jl#4]
There is this internal `_zero!` method defined, but why not just define and export `Base.empty!`?

**Comment by Jutho** [comment]
`empty!` is supposed to remove all elements from a collection, resulting in a collection with `length(empty!(a)) == 0`. That is not the same as zero-ing all elements. For example, `empty!` also doesn't work on `SparseMatrixCSC` from the SparseArrays standard library.

**Comment by Datseris** [comment]
Yeah, I understand that, but I am asking you to export `empty!` as that's what I am want: to remove all elements of a collection, and this already happening in the source code anyways.

**Comment by Jutho** [comment]
But `SparseArray` is a subtype of `AbstractArray` and should follow its general interface. For example, for the Base `Array` type, `empty!` only works on `Array{T,1}`, that is, `Vector{T}`, and there it actually reduces the length of the vector to zero. On instances of `Array{T,N}` for any `N>1` (or `N=0`), `empty!` gives an error message.

**Comment by matbesancon** [comment]
I've had this use case with other sparse array types, there should be a `zero!` function in SparseArrays or Base

**Comment by Jutho** [comment]
See my proposal for a unified vector interface at: https://github.com/Jutho/VectorInterface.jl
I plan to make at least my packages follow this interface, though this still needs to happen.

**Comment by Jutho** [comment]
I think this can now be closed, as the VectorInterface has been implemented, and so you can use `VectorInterface.zerovector!(a::SparseArray)`.
