### ISSUE TITLE
Triple Outer Product

### ISSUE THREAD

**Issue by ejmeitz** [Jutho/SparseArrayKit.jl#8]
Hello,

I'd like to use your library to calculate the outer product of 3 sparse vectors. In numpy I can do np.outer(np.outer(u,u),u) or similarly use einsum with a dense matrix in Julia but your library is one of the few that supports high dimensional sparse tensors. How can I do this operation with SparseArrays? 

I can define u = SparseArray{Float32}(undef,(5,1)) and get the sparse vector. I can do u * u' to get the first outer product but cannot get the third outer product to work.

And finally how can I contract this result with another rank 3 tensor that is not of the type SparseArray (I think this should be easy I'm just struggling to figure out the source code)?

**Comment by Jutho** [comment]
You can use `SparseArray` objects in combination with TensorOperations.jl and in particular the `@tensor` macro. Would this help you?

The outer product that you want is probably
```julia
@tensor outer[i,j,k] = u[i]*u[j]*u[k]
```

**Comment by ejmeitz** [comment]
Yeah that's what I would like to do, but I get an error: UndefVarError: IndexError not defined in contract!()

As an aside, the output to REPL is just printed with all the zeros right? The zeros aren't actually stored or used in the operation?

**Comment by Jutho** [comment]
No zeros are not used or stored. 

It's probably because you use size `(5,1)` for your vector `u`. In Julia, a vector has a single dimension, so its size is just `(5,)`. If you use `(5,1)`, then `u` is an object with two indices.

**Comment by Jutho** [comment]
But there is something wrong with that error message definitely. We will look into this.

**Comment by ejmeitz** [comment]
Yep just making it (5,) fixed it, thank you very much! I hope features from this library find their way into base sparse tensors are pretty common I feel.

**Comment by ejmeitz** [comment]
A little unrelated to the initial comment, but I have a quick question about tensor contraction with the result of the outer product.

I'm doing @tensor U = A[i,j,k] * outer[i,j,k].

My A tensor is not sparse and this only works if I make wrap A with a sparse array like SparseArray(A). Is this the intended way to do this operation or is there a better way to contract a non-sparse array with the sparse array?

Thanks!
