### ISSUE TITLE
Operations between SparseArrays and normal Arrays

### ISSUE THREAD

**Issue by ejmeitz** [Jutho/SparseArrayKit.jl#9]
I have a problem with a sparse tensor multiplied by a few dense vectors. This problem should be able to take advantage of sparsity in the main tensor when doing the multiplication; however, I am unable to use the @tensor macro's with mixed types. Is this intended? If I cast the vector to be a SparseArray the operation executes but much slower than I'd expect.

For example, where A is a SparseArray and u is a dense vector, what is the recommended way of doing this or is this not the intended use case for this library? Thanks!
```julia
@tensor begin
   K = A[i,j,k] * u[i] * u[j] * u[k]
end
```

**Comment by Jutho** [comment]
It is very hard to predict what the optimal strategy is for dealing with the mixed case, and this will depend on details such as the specific contraction, the sparsity of the sparse arrays involved, …

Among a whole range of strategies (for more complicated contractions), there will always be the strategies that amount to converting everything to sparse and using that implementation, or using everything to dense and using that implementation. In many cases, one of those two might even be optimal, or close to. However, as it is impossible to predict when this is the case, the mixed case is (at least for now) unsupported. A user, having more knowledge about the specific use case and sparsity patterns, should thus make the decision of either converting everything to dense or everything to sparse.
